### ISSUE TITLE
Retrieve mmsi from the full model

### ISSUE THREAD

**Issue by tkurki** [SignalK/aisreporter#11]
This no longer works with the current server because of changes in the configuration method.

It should try to retrieve mmsi from the full model so that it is independent from the configuration method. It could also try to retrieve the mmsi every once in a while so that a server restart or disable/enable cycle is not necessary.

**Comment by seabits-steve** [comment]
Could this be why when I try to use this, SignalK crashes with an error about not being able to read an MMSI value?

`Feb  3 06:38:38 grace signalk-server[11819]: /usr/lib/node_modules/signalk-server/node_modules/@signalk/aisreporter/index.js:31

Feb  3 06:38:38 grace signalk-server[11819]: var mmsi = app.config.settings.vessel.mmsi
Feb  3 06:38:38 grace signalk-server[11819]: ^

Feb  3 06:38:38 grace signalk-server[11819]: TypeError: Cannot read property 'mmsi' of undefined
Feb  3 06:38:38 grace signalk-server[11819]: at Object.plugin.start (/usr/lib/node_modules/signalk-server/node_modules/@signalk/aisreporter/index.js:31:42)
Feb  3 06:38:38 grace signalk-server[11819]: at err (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:179:18)
Feb  3 06:38:38 grace signalk-server[11819]: at FSReqWrap.oncomplete (fs.js:123:15)`

**Comment by tkurki** [comment]
This should now be fixed in version 0.0.4.
