### ISSUE TITLE
Reporter not sending position data

### ISSUE THREAD

**Issue by guyht** [SignalK/aisreporter#15]
Receiving data to OpenPlotter running on a RPI3 with an actisense NGT feeding data in.  Everything else working, and NMEA2k data appears to be correctly arriving in Signalk - all other apps and OpenCPN work as expected.

When Aisreporter was initially installed, it was sending data correctly to Marinetraffic, but it was using the wrong, default MMSI (123456789) - but I was able to correctly see my position on the Marinetraffic website.  When I updated my MMSI to the correct one, it stopped working, and on the plugin conf page, it shows the position AIS msg as an [object Object]

I tried some initial debugging but not too familiar with Signalk yet.  I tried resetting defaults.json - tried using a UUID instead of MMSI, tried using a blank defaults.json.  Restarted server each time but no dice.

Tried putting some log lines in aisreporter/index.js - by wrapping the 'msg' in this line (https://github.com/SignalK/aisreporter/blob/master/index.js#L60) with a JSON.stringify, it shows that msg is an empty Object, but not sure why this is, possibly an upstream error.  

Nothing showing up in the Logs (which are enabled in aisreporter plugin settings).

It appears that aisreporter is still correctly sending static data

Pls let me know what other info I can provide to help
Thx

![image](https://user-images.githubusercontent.com/385091/45248374-c435e280-b2c4-11e8-86af-0be3fd52631c.png)

**Comment by tkurki** [comment]
Sorry, I had forgotten about this issue.

Do you have all the required data? The position report depends on having
- navigation.position
- navigation.speedOverGround
- navigation.courseOverGroundTrue
- navigation.headingTrue

**Comment by tkurki** [comment]
What I said above is actually wrong, it does send data out even if some fields don't have data.

The `[object Object` that you see is just an error in the status message generation - if the timestamp is updating when you refresh the page it means that messages are being sent.

**Comment by tkurki** [comment]
Are you quite sure that data is not going out? I have an updated version waiting for review in a branch that will show the latest sent dynamic & static messages with timestamps.

**Comment by tkurki** [comment]
No response.
