### ISSUE TITLE
Feature request: add choice to send all vessels

### ISSUE THREAD

**Issue by joabakk** [SignalK/aisreporter#17]
Currently as I read the code, only self is sent. If self has no MMSI, or the server only has other AIS vessels, it could be good to to have a choice as "send all vessels". That way, a server could act as an AIS dispatcher station for Marinetraffic/AisHUB or other

**Comment by joabakk** [comment]
Actually, it is easier to set this up in kplex.

**Comment by itemir** [comment]
I was looking for something similar and found this issue. @joabakk , why did you think it is easier to do in kplex? I mean, it is for sure doable in different ways but I think it would be super cool if this plugin could replace [aisdispatcher](https://www.aishub.net/ais-dispatcher). 

For instance, I currently send my AIS data to both Marine Traffic and AIS Hub. And when I say AIS data, I don't mean only my boat but everything around me. For this, I get the data into Signal K and then also separately use aisdispatcher. If Signal K did everything it would be much better.

**Comment by joabakk** [comment]
I do agree, but I could not find the time to do the PR. Perhaps you can @itemir ?

**Comment by tkurki** [comment]
Note that creating 0183 messages makes sense only if the original AIS data is not in 0183 format. Use AIS forwarder plugin otherwise.

**Comment by itemir** [comment]
Thanks, airforwarder is what I was looking for. Even if the original AIS data is not in 0183 format, looks like it can support it via  signalk-n2kais-to-nmea0183 plugin.
