### ISSUE TITLE
Crashes on null when calling ".toUpperCase()"

### ISSUE THREAD

**Issue by wxe** [SignalK/aisreporter#19]
signalk_1   | TypeError: Cannot read property 'toUpperCase' of null
signalk_1   |     at AisEncode.PutStr (/home/node/.signalk/node_modules/ggencoder/lib/GG-AisEncode.js:261:19)
signalk_1   |     at new AisEncode (/home/node/.signalk/node_modules/ggencoder/lib/GG-AisEncode.js:164:22)
signalk_1   |     at sendStaticPartOne (/home/node/.signalk/node_modules/@signalk/aisreporter/dist/index.js:170:27)
signalk_1   |     at sendStaticReport (/home/node/.signalk/node_modules/@signalk/aisreporter/dist/index.js:65:25)
signalk_1   |     at Object.start (/home/node/.signalk/node_modules/@signalk/aisreporter/dist/index.js:68:17)
signalk_1   |     at doPluginStart (/home/node/signalk/lib/interfaces/plugins.js:259:20)
signalk_1   |     at err (/home/node/signalk/lib/interfaces/plugins.js:398:21)
signalk_1   |     at /home/node/signalk/node_modules/graceful-fs/graceful-fs.js:61:14
signalk_1   |     at FSReqWrap.args [as oncomplete] (fs.js:140:20)

**Comment by tkurki** [comment]
Do you have vessel name configured?

**Comment by wxe** [comment]
Yes; all fields are set.
