### ISSUE TITLE
Wrong Measures

### ISSUE THREAD

**Issue by spidgrou** [SignalK/aisreporter#20]
Hi,
there is something that I didn't understand.
I put in the SignalK all the details of my boat and the plugin sends other data.
Can you help me to better understand please?

On the img_1 you can see the screenshot of my configuration.
On the img_2 the convertion of the AIVDM String.

![Img_1](https://user-images.githubusercontent.com/42083306/103325739-01d06200-4ab2-11eb-8192-4b26cc8d46b1.jpg)
![Img_2](https://user-images.githubusercontent.com/42083306/103325740-04cb5280-4ab2-11eb-806b-19c807a0c251.jpg)

Thanks

**Comment by joabakk** [comment]
Nothing wrong here as far as I see. A is distance from bow to GPS (0), B aft to GPS(15m), C port to GPS (3m) and D stbd to GPS (3m) since you have stated that the GPS is 0m form CENTER and 0m from BOW
